import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

import { Footer } from '@/components/footer'
import clsx from 'clsx'

const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi",
  weight: "300 600",
}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(`font-sans bg-stone-900 selection:bg-blue-400/40 selection:text-white antialiased`, 
	  satoshi.variable, 
	)}>
       <svg
          className="pointer-events-none fixed isolate z-50 opacity-70 mix-blend-soft-light"
          width="100%"
          height="100%"
        >
          <filter id="noise">
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.80"
              numOctaves="4"
              stitchTiles="stitch"
            />
          </filter>
          <rect width="100%" height="100%" filter="url(#noise)" />
        </svg>

        <div className="grid grid-cols-[1fr_min(640px,100%)_1fr] relative z-10 gap-y-4 px-4 xl:grid-cols-[1fr_minmax(auto,15rem)_min(640px,100%)_minmax(auto,15rem)_1fr] xl:gap-x-9 xl:px-0 [&>*]:col-start-2 xl:[&>*]:col-start-3">
         {children}

	 <Footer />
	</div>
      </body>
    </html>
  );
}
